# Generated by Django 4.2.5 on 2023-12-22 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_relationship_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follwing_relationships', to=settings.AUTH_USER_MODEL, verbose_name='팔로우를 요청한 사람'),
        ),
    ]
